
// 
import type { Metadata } from "next";
import {setRequestLocale} from 'next-intl/server';
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import { Changa, Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};


const changa = Changa({
  subsets: ['arabic'],
  weight: ['400', '500', '700'],
  variable: '--font-changa',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter',
  display: 'swap',
});

export default async function ProfileLayout({ children, params }: { children: React.ReactNode; params: Promise<{locale: string}>;}) {

  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <div lang={locale}>
      <div className={`${changa.className} ${inter.className} antialiased`}>
        <NextIntlClientProvider>
        <Toaster position="top-right" reverseOrder={false} />
          <AuthProvider>
            {children}
          </AuthProvider>
        </NextIntlClientProvider>
      </div>
    </div>
  );
}