

// import { Changa, Inter } from 'next/font/google';
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Login/Register",
  description: "Generated by create next app",
};

// const changa = Changa({
//   subsets: ['arabic'],
//   weight: ['400', '500', '700'],
//   variable: '--font-changa',
//   display: 'swap',
// });

// const inter = Inter({
//   subsets: ['latin'],
//   weight: ['400', '500', '700'],
//   variable: '--font-inter',
//   display: 'swap',
// });
export default function AuthLayout({children}: {children: React.ReactNode;}) {
  return (
    <div>
      <Toaster position="top-right" reverseOrder={false} />
      {children}
    </div>
  );
}
